# Generated by Django 4.1.5 on 2023-01-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_id', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=120)),
                ('typology', models.CharField(default='', max_length=25)),
                ('price', models.IntegerField()),
                ('area', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('link', models.URLField(default='', unique=True)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('province', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('condition', models.CharField(default='', max_length=50)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['-created'], name='scraper_apa_created_88feaa_idx'),
        ),
    ]
